// eslint-disable-next-line import/no-anonymous-default-export
export default {
  services: [
    {
      'id':1,
      'name':'Reparación y mantenimiento',
      'image': 'https://apiweb.netlify.app/images/soldi/service1.png',
      'detail': 'https://apiweb.netlify.app/images/detail/detail-1.jpg',
      'price':'',
      'breve1': '',
      'breve2': '',
      'breve3': '',
      'buttontype':'solicitar',
      'tipo':'servicios',
      'mensaje':'Un%20gusto%20empresa%20Soldinoxtig%2C%20quisiera%20m%C3%A1s%20informacion%20sobre%20el%20servicio%20de%20',
      'column':'one',
      'link':'reparación-y-mantenimiento'
    },
    {
      'id':2,
      'name':'Soldadura TIG',
      'image': 'https://apiweb.netlify.app/images/soldi/service2.png',
      'detail': 'https://apiweb.netlify.app/images/detail/detail-2.jpg',
      'price':'',
      'breve1': 'Soldadura TIG, acero, aluminio, titanio, magnesio, cobre berilio, bronce berilio.',
      'breve2': '',
      'breve3': '',
      'buttontype':'solicitar',
      'tipo':'servicios',
      'mensaje':'Un%20gusto%20empresa%20Soldinoxtig%2C%20quisiera%20m%C3%A1s%20informacion%20sobre%20el%20servicio%20de%20',
      'column':'two',
      'link':'soldadura-tig'
    },
    {
      'id':3,
      'name':'Remodelación en general',
      'image': 'https://apiweb.netlify.app/images/soldi/service3.png',
      'detail': 'https://apiweb.netlify.app/images/detail/detail-3.jpg',
      'price':'',
      'breve1': '',
      'breve2': ' ',
      'breve3': '',
      'buttontype':'solicitar',
      'tipo':'servicios',
      'mensaje':'Un%20gusto%20empresa%20Soldinoxtig%2C%20quisiera%20m%C3%A1s%20informacion%20sobre%20el%20servicio%20de%20',
      'column':'one',
      'link':'remodelación-en-general'
    },
    {
      'id':4,
      'name':'Todo tipo de enchapes en acero inoxidable',
      'image': 'https://apiweb.netlify.app/images/soldi/service4.png',
      'detail': 'https://apiweb.netlify.app/images/detail/detail-4.jpg',
      'price':'',
      'breve1': '',
      'breve2': '',
      'buttontype':'solicitar',
      'tipo':'servicios',
      'mensaje':'Un%20gusto%20empresa%20Soldinoxtig%2C%20quisiera%20m%C3%A1s%20informacion%20sobre%20el%20servicio%20de%20',
      'column':'two',
      'link':'todo-tipo-acero'
    },
    {
      'id':5,
      'name':'Diseño CAD',
      'image': 'https://apiweb.netlify.app/images/soldi/service5.png',
      'detail': 'https://apiweb.netlify.app/images/detail/detail-5.jpg',
      'price':'',
      'breve1': ' ',
      'breve2': ' ',
      'breve3': '',
      'buttontype':'solicitar',
      'tipo':'servicios',
      'mensaje':'Un%20gusto%20empresa%20Soldinoxtig%2C%20quisiera%20m%C3%A1s%20informacion%20sobre%20el%20servicio%20de%20',
      'column':'one',
      'link':'diseno-cad'
    },
    
  ],
};